name: Flutter CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-version: ['2.5.3', '2.8.0', 'latest']
        os: [ubuntu-latest, macos-latest, windows-latest]
        working-directory: ['.'] 

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Cache Flutter SDK
      uses: actions/cache@v2
      with:
        path: ~/.pub-cache
        key: ${{ runner.os }}-pub-cache-${{ matrix.flutter-version }}
        restore-keys: |
          ${{ runner.os }}-pub-cache-

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ matrix.flutter-version }}

    - name: Install dependencies
      run: flutter pub get
      working-directory: ${{ matrix.working-directory }}

    - name: Format code
      run: dart format --set-exit-if-changed .
      working-directory: ${{ matrix.working-directory }}

    - name: Analyze code
      run: dart analyze .
      working-directory: ${{ matrix.working-directory }}

    - name: Run lint
      run: flutter analyze
      working-directory: ${{ matrix.working-directory }}

    - name: Run tests
      run: flutter test --coverage
      working-directory: ${{ matrix.working-directory }}

    - name: Upload code coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage/lcov.info

    - name: Build APK
      run: flutter build apk --release
      working-directory: ${{ matrix.working-directory }}

    - name: Build iOS
      if: matrix.os == 'macos-latest'
      run: flutter build ios --release --no-codesign
      working-directory: ${{ matrix.working-directory }}

    - name: Archive APK
      uses: actions/upload-artifact@v2
      with:
        name: apk
        path: build/app/outputs/flutter-apk/app-release.apk

    - name: Archive iOS build
      if: matrix.os == 'macos-latest'
      uses: actions/upload-artifact@v2
      with:
        name: ios
        path: build/ios/ipa
